package com.bubbleladder.resetlabv432;
import android.app.*;import android.content.*;import android.os.*;import java.util.concurrent.*;
public class AutoDrawService extends Service{
    public static final String CHANNEL_ID="reset_lab_v432_live";public static final int NOTI_ID=4320;private final Handler h=new Handler(Looper.getMainLooper());private final ExecutorService ex=Executors.newSingleThreadExecutor();private boolean syncing=false;private int retry=0;private static final int MAX_RETRY=12;private static final long RETRY_MS=10000L;
    private final Runnable tick=new Runnable(){public void run(){update();h.postDelayed(this,ResetCore.millisToNextDraw()<=30000?1000:5000);}};private final Runnable fetch=new Runnable(){public void run(){sync();}};
    public void onCreate(){super.onCreate();channel();startForeground(NOTI_ID,notification());h.post(tick);h.post(fetch);}public int onStartCommand(Intent i,int f,int id){if(!ResetCore.prefs(this).getBoolean(ResetCore.K_AUTO,true)){stopSelf();return START_NOT_STICKY;}if(!syncing){h.removeCallbacks(fetch);h.post(fetch);}return START_STICKY;}
    private void sync(){if(syncing)return;syncing=true;ex.execute(()->{boolean advanced=false;try{ResetCore.SyncResult r=ResetCore.sync(this);advanced=r.newRound;}catch(Exception ignored){}final boolean ok=advanced;h.post(()->{syncing=false;sendBroadcast(new Intent(ResetCore.ACTION_UPDATED).setPackage(getPackageName()));update();h.removeCallbacks(fetch);if(ok){retry=0;schedule();}else if(retry<MAX_RETRY){retry++;h.postDelayed(fetch,RETRY_MS);}else{retry=0;schedule();}});});}
    private void schedule(){h.postDelayed(fetch,ResetCore.millisToNextDraw()+7000);}private void channel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(CHANNEL_ID,"V4.3.2 Reset Lab",NotificationManager.IMPORTANCE_LOW);getSystemService(NotificationManager.class).createNotificationChannel(c);}}
    private Notification notification(){Intent open=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,0,open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);ResetCore.EngineView[] e=ResetCore.views(this);StringBuilder s=new StringBuilder("다음 "+ResetCore.countdownText());for(int i=0;i<e.length;i++){if(e[i].analysis!=null)s.append(" · ").append(i==0?"N":String.valueOf(ResetCore.INTERVAL[i])).append(":").append(ResetCore.COMBO[e[i].analysis.exclude]);}if(retry>0)s.append(" · 새회차확인 ").append(retry).append("/").append(MAX_RETRY);Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CHANNEL_ID):new Notification.Builder(this);return b.setSmallIcon(android.R.drawable.ic_popup_sync).setContentTitle("보글사다리3 V4.3.2 Reset Lab").setContentText(s.toString()).setStyle(new Notification.BigTextStyle().bigText(s.toString())).setOngoing(true).setOnlyAlertOnce(true).setContentIntent(pi).build();}
    private void update(){((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(NOTI_ID,notification());}public void onDestroy(){h.removeCallbacksAndMessages(null);ex.shutdownNow();super.onDestroy();}public android.os.IBinder onBind(Intent i){return null;}
}
