package com.bubbleladder.resetlabv432;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.*;import android.text.InputType;import android.view.*;import android.widget.*;import org.json.JSONObject;import java.io.*;import java.text.SimpleDateFormat;import java.util.*;import java.util.concurrent.*;

public class MainActivity extends Activity{
    private static final int REQ_EXPORT=4321,REQ_IMPORT=4322,REQ_NOTI=4323;private final Handler h=new Handler(Looper.getMainLooper());private final ExecutorService ex=Executors.newSingleThreadExecutor();
    private TextView countdown,status,bg,summary,details,recent;private EditText stake,odds;private CheckBox auto;private Button refresh,save,backup,restore,reset;
    private final BroadcastReceiver receiver=new BroadcastReceiver(){public void onReceive(Context c,Intent i){reload();}};private final Runnable tick=new Runnable(){public void run(){if(countdown!=null)countdown.setText(ResetCore.countdownText());h.postDelayed(this,1000);}};
    public void onCreate(Bundle b){super.onCreate(b);setContentView(ui());loadSettings();bind();registerUpdates();requestNoti();h.post(tick);if(ResetCore.prefs(this).getBoolean(ResetCore.K_AUTO,true))startAuto();reload();}
    private View ui(){ScrollView sv=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(14),dp(16),dp(14),dp(30));r.setBackgroundColor(Color.rgb(7,19,26));sv.addView(r);
        r.addView(tv("보글사다리3 · V4.3.2 Reset Lab",24,Color.WHITE,true));TextView sub=tv("무리셋 / 3회 / 4회 / 6회 / 7회 리셋을 같은 실제 회차에서 동시검증",12,Color.rgb(110,231,183),false);sub.setPadding(0,dp(4),0,dp(14));r.addView(sub);
        LinearLayout c=card();c.addView(tv("다음 추첨까지",12,Color.GRAY,false));countdown=tv("--:--",38,Color.rgb(56,189,248),true);c.addView(countdown);bg=tv("백그라운드 확인 중",12,Color.LTGRAY,false);c.addView(bg);r.addView(c);
        LinearLayout ctl=card();refresh=button("🔄 지금 추첨 / Reset Lab 동시분석",Color.rgb(5,150,105));ctl.addView(refresh,new LinearLayout.LayoutParams(-1,dp(54)));auto=new CheckBox(this);auto.setText("백그라운드 자동추첨 ON");auto.setTextColor(Color.WHITE);ctl.addView(auto);status=tv("조회 준비",12,Color.LTGRAY,false);ctl.addView(status);r.addView(ctl);
        LinearLayout s=card();s.addView(section("5개 엔진 실전 비교"));summary=tv("-",15,Color.WHITE,false);summary.setLineSpacing(0,1.35f);s.addView(summary);r.addView(s);
        LinearLayout d=card();d.addView(section("현재 추천 · 리셋 주기 · 분석데이터"));details=tv("-",13,Color.rgb(226,232,240),false);details.setLineSpacing(0,1.3f);d.addView(details);r.addView(d);
        LinearLayout bet=card();bet.addView(section("고정배팅 · 공통 설정"));LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);stake=input("5000");odds=input("1.95");stake.setInputType(InputType.TYPE_CLASS_NUMBER);odds.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);row.addView(stake,new LinearLayout.LayoutParams(0,dp(52),1));LinearLayout.LayoutParams op=new LinearLayout.LayoutParams(0,dp(52),1);op.setMargins(dp(8),0,0,0);row.addView(odds,op);bet.addView(row);save=button("설정 저장 · 최소 5,000원",Color.rgb(30,64,175));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(48));sp.setMargins(0,dp(8),0,0);bet.addView(save,sp);r.addView(bet);
        LinearLayout rc=card();rc.addView(section("마스터 최근 15회"));recent=tv("-",13,Color.WHITE,false);rc.addView(recent);r.addView(rc);
        LinearLayout io=card();io.addView(section("Reset Lab 백업 / 복원"));LinearLayout br=new LinearLayout(this);br.setOrientation(LinearLayout.HORIZONTAL);backup=button("💾 백업",Color.rgb(21,128,61));restore=button("📂 복원",Color.rgb(109,40,217));br.addView(backup,new LinearLayout.LayoutParams(0,dp(48),1));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(0,dp(48),1);rp.setMargins(dp(8),0,0,0);br.addView(restore,rp);io.addView(br);reset=button("실험 전체 초기화",Color.rgb(127,29,29));LinearLayout.LayoutParams rr=new LinearLayout.LayoutParams(-1,dp(46));rr.setMargins(0,dp(8),0,0);io.addView(reset,rr);r.addView(io);
        r.addView(tv("※ 리셋 엔진은 실제 누적 승률을 지우지 않습니다. 정해진 주기가 오면 그 엔진의 분석 history만 그 시점의 API 최신 스냅샷으로 교체합니다. 그래서 수동 초기화 효과를 기록 손실 없이 비교할 수 있습니다.",11,Color.GRAY,false));return sv;}
    private void bind(){refresh.setOnClickListener(v->sync());save.setOnClickListener(v->saveSettings());auto.setOnCheckedChangeListener((b,on)->{ResetCore.prefs(this).edit().putBoolean(ResetCore.K_AUTO,on).apply();if(on)startAuto();else stopService(new Intent(this,AutoDrawService.class));bg();});backup.setOnClickListener(v->export());restore.setOnClickListener(v->importFile());reset.setOnClickListener(v->confirmReset());}
    private void loadSettings(){android.content.SharedPreferences p=ResetCore.prefs(this);stake.setText(String.valueOf(Math.max(5000,p.getInt(ResetCore.K_BASE_STAKE,5000))));odds.setText(String.valueOf(p.getFloat(ResetCore.K_ODDS,1.95f)));auto.setChecked(p.getBoolean(ResetCore.K_AUTO,true));bg();}
    private int stake(){try{return Math.max(5000,Integer.parseInt(stake.getText().toString().trim()));}catch(Exception e){return 5000;}}private double odds(){try{return Math.max(1.01,Double.parseDouble(odds.getText().toString().trim()));}catch(Exception e){return 1.95;}}
    private void saveSettings(){ResetCore.prefs(this).edit().putInt(ResetCore.K_BASE_STAKE,stake()).putFloat(ResetCore.K_ODDS,(float)odds()).apply();stake.setText(String.valueOf(stake()));Toast.makeText(this,"저장 완료",Toast.LENGTH_SHORT).show();}
    private void sync(){saveSettings();refresh.setEnabled(false);status.setText("5개 엔진 동시 분석 중...");ex.execute(()->{try{ResetCore.SyncResult x=ResetCore.sync(this);h.post(()->{render(x.engines,x.master,x.snapshotSize);status.setText("● 완료 · "+new SimpleDateFormat("HH:mm:ss",Locale.KOREA).format(new Date()));status.setTextColor(Color.rgb(52,211,153));refresh.setEnabled(true);});}catch(Exception e){h.post(()->{status.setText("조회 실패: "+e.getMessage());status.setTextColor(Color.rgb(248,113,113));refresh.setEnabled(true);});}});}
    private void reload(){ex.execute(()->{ResetCore.EngineView[] e=ResetCore.views(this);List<ResetCore.Result> m=ResetCore.master(this);int snap=ResetCore.prefs(this).getInt(ResetCore.K_SNAPSHOT,0);h.post(()->{render(e,m,snap);bg();});});}
    private void render(ResetCore.EngineView[] e,List<ResetCore.Result> master,int snap){StringBuilder a=new StringBuilder();for(int i=0;i<e.length;i++){ResetCore.EngineView v=e[i];String rate=v.total==0?"-":v.hit+"/"+v.total+" = "+ResetCore.pct((double)v.hit/v.total);String r20=v.recent20N==0?"-":v.recent20Hit+"/"+v.recent20N+" = "+ResetCore.pct((double)v.recent20Hit/v.recent20N);a.append(i==0?"🧱 ":"🔄 ").append(ResetCore.ENGINE[i]).append(" · ").append(rate).append("\n   최근20 ").append(r20).append(" · ").append(ResetCore.signed(v.profit));if(i<e.length-1)a.append("\n\n");}summary.setText(a.toString());
        StringBuilder d=new StringBuilder();d.append("API 새로받은 스냅샷: ").append(snap).append("개\n마스터 누적: ").append(master.size()).append("개\n\n");for(int i=0;i<e.length;i++){ResetCore.EngineView v=e[i];d.append("● ").append(ResetCore.ENGINE[i]);if(i>0)d.append(" · 진행 ").append(v.counter).append("/").append(v.interval).append(" · 리셋 ").append(v.resets).append("회");d.append("\n   분석데이터 ").append(v.dataSize).append("개");if(v.analysis!=null){d.append(" · 최근480 사용 ").append(v.analysis.count).append("개\n   제외 ").append(ResetCore.COMBO[v.analysis.exclude]).append(" → ").append(v.analysis.triple).append("\n   ").append(v.analysis.grade).append(" · ").append(v.analysis.mode).append(" · 결정표 ").append(v.analysis.decisiveVotes).append("/12");}else d.append(" · 분석 대기");if(i<e.length-1)d.append("\n\n");}details.setText(d.toString());
        List<ResetCore.Result> r=ResetCore.recentDesc(master,15);StringBuilder z=new StringBuilder();for(int i=0;i<r.size();i++){ResetCore.Result q=r.get(i);z.append(i==0?"최신  ":"      ").append(q.date).append(" ").append(q.round).append("회 · ").append(ResetCore.COMBO[q.combo]);if(i<r.size()-1)z.append("\n");}recent.setText(z.length()==0?"데이터 없음":z.toString());}
    private void startAuto(){Intent i=new Intent(this,AutoDrawService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}private void bg(){boolean on=ResetCore.prefs(this).getBoolean(ResetCore.K_AUTO,true);if(bg!=null){bg.setText(on?"● 백그라운드 ON":"○ 백그라운드 OFF");bg.setTextColor(on?Color.rgb(52,211,153):Color.GRAY);}}
    private void registerUpdates(){IntentFilter f=new IntentFilter(ResetCore.ACTION_UPDATED);if(Build.VERSION.SDK_INT>=33)registerReceiver(receiver,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(receiver,f);}private void requestNoti(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},REQ_NOTI);}
    private void export(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"ResetLabV432_"+new SimpleDateFormat("yyyyMMdd_HHmm",Locale.KOREA).format(new Date())+".json");startActivityForResult(i,REQ_EXPORT);}private void importFile(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,REQ_IMPORT);}
    protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(res!=RESULT_OK||data==null||data.getData()==null)return;Uri u=data.getData();try{if(req==REQ_EXPORT){OutputStream o=getContentResolver().openOutputStream(u);o.write(ResetCore.backup(this).toString(2).getBytes("UTF-8"));o.close();Toast.makeText(this,"백업 완료",Toast.LENGTH_LONG).show();}else if(req==REQ_IMPORT){BufferedReader br=new BufferedReader(new InputStreamReader(getContentResolver().openInputStream(u),"UTF-8"));StringBuilder s=new StringBuilder();String line;while((line=br.readLine())!=null)s.append(line);br.close();ResetCore.restore(this,new JSONObject(s.toString()));loadSettings();reload();Toast.makeText(this,"복원 완료",Toast.LENGTH_LONG).show();}}catch(Exception e){Toast.makeText(this,"처리 실패: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
    private void confirmReset(){new AlertDialog.Builder(this).setTitle("Reset Lab 전체 초기화").setMessage("5개 엔진의 승률·수익·분석데이터를 모두 처음부터 다시 시작합니다.").setNegativeButton("취소",null).setPositiveButton("초기화",(x,w)->{ResetCore.resetExperiment(this);recreate();}).show();}
    private LinearLayout card(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(14),dp(14),dp(14),dp(14));GradientDrawable g=new GradientDrawable();g.setColor(Color.rgb(15,30,46));g.setCornerRadius(dp(18));x.setBackground(g);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(12));x.setLayoutParams(p);return x;}private TextView section(String s){TextView v=tv(s,16,Color.WHITE,true);v.setPadding(0,0,0,dp(10));return v;}private TextView tv(String s,int z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(b)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}private Button button(String s,int c){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setAllCaps(false);GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(12));b.setBackground(g);return b;}private EditText input(String s){EditText e=new EditText(this);e.setText(s);e.setTextColor(Color.WHITE);e.setTextSize(16);e.setPadding(dp(12),0,dp(12),0);GradientDrawable g=new GradientDrawable();g.setColor(Color.rgb(30,41,59));g.setCornerRadius(dp(12));e.setBackground(g);return e;}private int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}protected void onDestroy(){h.removeCallbacksAndMessages(null);try{unregisterReceiver(receiver);}catch(Exception ignored){}ex.shutdownNow();super.onDestroy();}
}
